"""
Append-only audit row for a single (BOM × strategy × graph_aware) optimizer invocation.

BENCH-01 (Phase 4). Benchmark invocation produces 20 rows per run_id (10 BOMs × 2 graph_aware).
D-09: run_id + timestamp keyed; /benchmark/summary defaults to latest run_id.
"""
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, JSON
from sqlalchemy.sql import func
from app.core.database import Base


class OptimizationRun(Base):
    __tablename__ = "optimization_runs"

    id = Column(Integer, primary_key=True, index=True)

    # Run grouping (D-09)
    run_id = Column(Integer, nullable=False, index=True)
    run_tag = Column(String(50), nullable=False, default="benchmark")
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    # Input identity
    bom_name = Column(String(100), nullable=False, index=True)
    bom_items_json = Column(JSON, nullable=False)

    # Strategy + flag (BENCH-01 + D-02)
    strategy = Column(String(20), nullable=False, default="balanced")
    graph_aware = Column(Boolean, nullable=False, index=True)

    # Disruption scenario label: 'nominal'|'stress'|'targeted'
    scenario = Column(String(20), nullable=True, index=True)
    # Benchmark arm label. The arm string encodes BOTH the algorithm and the
    # OFFER POOL it shopped, because the pool is half of what makes a baseline
    # comparison fair and burying it in prose is how the published headline came
    # to compare a globally-shopping greedy against a domestic-only MILP:
    #   'greedy'         naive per-line cheapest, FULL international pool
    #   'greedy_add'     Kuehn-Hamburger ADD heuristic, FULL international pool
    #   'greedy_dom'     naive per-line cheapest, DOMESTIC-only pool (us_only=True)
    #   'greedy_add_dom' ADD heuristic, DOMESTIC-only pool (us_only=True)
    #   'milp'           CP-SAT; `graph_aware` splits it into blind vs graph-aware.
    #                    Its pool is domestic-only (balanced.us_only_sourcing=True).
    # The `_dom` arms are the pool-MATCHED baselines: they shop the same catalogue
    # the MILP is allowed, so `milp vs greedy_add_dom` is the apples-to-apples
    # number and `milp vs greedy` is the naive-globally-shopping contrast.
    #
    # NOTE ON THE WIDTH. This is String(24), not String(12), purely so the
    # declaration can hold 'greedy_add_dom'. No migration accompanies the change
    # and none is needed: the column was added by migration 0005 with `add_column`,
    # so in the deployed SQLite database it is plain `TEXT` with no length at all
    # (verify: `sqlite3 backend/supply_chain.db ".schema optimization_runs"`), and
    # SQLite does not enforce VARCHAR length on any backend it serves. The width
    # here only affects the DDL a fresh `create_all` emits, where VARCHAR(24) and
    # VARCHAR(12) behave identically. Nothing in the stored schema changes.
    arm = Column(String(24), nullable=True, index=True)

    # Pre-projected scalars (BENCH-01 explicit requirement)
    total_cost_usd = Column(Float, nullable=False)
    total_component_cost_usd = Column(Float)
    total_transport_cost_usd = Column(Float)
    eta_p10_days = Column(Float)
    eta_p50_days = Column(Float, nullable=False)
    eta_p90_days = Column(Float)
    co2_kg = Column(Float, nullable=False)
    # DEPRECATED — DEAD COLUMN. Do NOT read this; use `plan_cascade_risk` instead.
    #
    # Defined as 1 - median fulfillment of the WHOLE distributor network under the
    # Monte Carlo. 97.7% of components in this catalogue are carried by two or more
    # distributors, so the median trial fulfils every line and the expression is
    # identically 0.0. It is 0.0 in all 234 rows ever written, including the very
    # first run — it has never once been non-zero, and it cannot be: the definition
    # is degenerate on any catalogue with real supplier redundancy, at every
    # percentile, not just the median.
    #
    # As of the 2026-08 functionality audit nothing in app/ reads it. It kept
    # `/benchmark/cascade-heatmap` returning `{"points": []}` against a fully
    # populated database and pinned `cascade_risk_delta_pct` at 0.0 for every BOM.
    # The column is retained only because it is NOT NULL on an existing table with
    # 234 rows; dropping it needs a migration and a benchmark re-run.
    cascade_risk_score = Column(Float, nullable=False)
    # THE LIVE ONE. Cascade risk of the SELECTED sourcing plan — the same 1 - median
    # fulfillment, but with the supplying pool restricted to the distributors the plan
    # actually chose, so a line sourced from one chosen supplier is correctly a single
    # point of failure. Populated with real variance (0.0 / 0.25 / 0.5 / 0.75 / 1.0).
    plan_cascade_risk = Column(Float, nullable=True)
    # Number of distinct suppliers used in the selected plan
    n_distinct_suppliers = Column(Integer, nullable=True)
    # Number of purchase orders generated by the selected plan
    n_orders = Column(Integer, nullable=True)

    # Full Monte Carlo payload for dashboard distribution plot (BENCH-04)
    monte_carlo_samples = Column(JSON)   # list[float], trimmed to 200 points
    mc_cvar_95 = Column(Float)

    # ── The measures that keep discriminating after mc_cvar_95 saturates ──────
    # OUTSTANDING_WORK.md item 13. `cost_inflation = 1 + (unfulfillable_share) *
    # EMERGENCY_COST_PREMIUM` is bounded, so `mc_cvar_95` — a mean over the worst-5%
    # tail of it — tops out at `1 + premium` (= 1.15 at the default) and STOPS
    # MOVING. Under `stress_factor=3` most benchmark plans sit on that ceiling, so
    # two arms print the identical 1.15 while being very differently exposed.
    # A tie at the ceiling is a CEILING, not a finding of equal risk.
    #
    # These four are computed by `graph/simulation.run_monte_carlo` and were
    # persisted nowhere until 2026-08-28, which is why 18 published CVaR cells tied
    # unflagged. They are means over ALL scenarios rather than over the tail, so
    # they keep resolving exactly where `mc_cvar_95` stops.
    #   mc_p_shortfall        P(>= 1 BOM line unfulfillable)
    #   mc_p_total_shortfall  P(EVERY line unfulfillable) — the event the tail is made of
    #   mc_cvar_95_ceiling    structural max of mc_cvar_95 for this row = 1 + premium
    #   mc_cvar_95_saturated  mc_cvar_95 IS at that ceiling; never read a tie here as
    #                         evidence of equal exposure — read the two p_* columns
    mc_p_shortfall = Column(Float, nullable=True)
    mc_p_total_shortfall = Column(Float, nullable=True)
    mc_cvar_95_ceiling = Column(Float, nullable=True)
    mc_cvar_95_saturated = Column(Boolean, nullable=True)

    # Feed status at run time (D-10 static-fallback mode tag)
    feeds_available = Column(JSON)        # {"gpr": bool, "acled": bool, ...}

    # Selected distributors snapshot — for "Where Graph-Aware Loses" narrative
    selected_distributor_ids = Column(JSON)
    selected_distributor_names = Column(JSON)
