"""`docs/RESEARCH_TECHNIQUES.md` Section 3.4 must agree with `docs/newsvendor.json`.

WHY THIS FILE EXISTS
---------------------
Section 3.4 is the newsvendor headline: beats every stocking baseline across tens of
thousands of held-out decisions, ~4% against the toughest (Scarf min-max) with a paired
bootstrap CI excluding zero, and the finding that `zero` wins MASE on this panel while being
the WORST policy on decision cost. Every figure is real -- `run_panel_evaluation` computes
all of them from the committed Monash car-parts panel -- but until now nothing regenerated
them and nothing checked the doc still said what the code says.
`backend/tests/test_docs_match_artifacts.py` names the docs it guards and explicitly does
NOT include `RESEARCH_TECHNIQUES.md`. This file is that missing gate for Section 3.4 only.

THE FAILURE MODE THIS GUARDS AGAINST, NAMED EXPLICITLY. This repo has already been bitten
by comparing one doc against another: `test_docs_match_artifacts.py` once found
`MODEL_CI.md` compared against `leakage_progression.json` while BOTH were stale together,
agreeing with each other and disagreeing with the deployed model. So every assertion below
reads `docs/newsvendor.json` -- the artifact `run_panel_evaluation` (the served code) itself
produced -- and never reads one doc to check another. `docs/newsvendor.json` is generated by
`backend/seeds/run_newsvendor.py`, which calls `app.optimization.newsvendor.run_panel_evaluation`
directly and writes exactly what it returns; there is no hand-editing step between the code
and the artifact for this test to be fooled by.

WHAT THIS FILE DOES NOT DO. It does not re-run the evaluation (`~17s` across the five
configurations Section 3.4 quotes -- see `run_newsvendor.py`'s docstring) and does not import
`app.optimization.newsvendor`. It reads two committed files and compares them. If the
artifact is stale, regenerate it with
`cd backend && ./venv/bin/python -m seeds.run_newsvendor` and re-run this file.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

BACKEND_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_ROOT.parent
DOCS = REPO_ROOT / "docs"

ARTIFACT_PATH = DOCS / "newsvendor.json"
DOC_PATH = DOCS / "RESEARCH_TECHNIQUES.md"

#: Formatting matched to the doc's own convention for each column (see the fixtures below).
def f5(x: float) -> str:
    return f"{x:.5f}"


def f4(x: float) -> str:
    return f"{x:.4f}"


def f2(x: float) -> str:
    return f"{x:.2f}"


def pct1(x: float) -> str:
    return f"{x:.1f}"


# ── Fixtures ─────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def artifact() -> dict:
    if not ARTIFACT_PATH.is_file():
        pytest.skip(
            f"{ARTIFACT_PATH} not generated; run "
            "`cd backend && ./venv/bin/python -m seeds.run_newsvendor`"
        )
    return json.loads(ARTIFACT_PATH.read_text())


@pytest.fixture(scope="module")
def primary(artifact: dict) -> dict:
    return artifact["primary"]


@pytest.fixture(scope="module")
def doc_text() -> str:
    if not DOC_PATH.is_file():
        pytest.skip(f"{DOC_PATH} missing")
    return DOC_PATH.read_text()


@pytest.fixture(scope="module")
def section(doc_text: str) -> str:
    """Section 3.4 only -- the region this generator and this test own.

    Normalises the Unicode minus sign (U+2212, used throughout this doc's prose for
    negative numbers) to an ASCII hyphen, so a plain `f"{x:.5f}"` built from the artifact
    can be found by substring search without every assertion re-deriving the typographic
    convention.
    """
    m = re.search(
        r"### 3\.4 Newsvendor critical fractile.*?(?=\n### 3\.5|\n## Track 4|\Z)",
        doc_text,
        re.DOTALL,
    )
    assert m, "Section 3.4 heading not found in RESEARCH_TECHNIQUES.md -- has it been renamed?"
    return m.group(0).replace("−", "-")


# ── The artifact itself must be the shape the doc claims ──────────────────────

def test_the_artifact_carries_every_configuration_the_doc_quotes(artifact: dict) -> None:
    for key in (
        "primary",
        "sensitivity_line_down",
        "sensitivity_review_period_3",
        "sensitivity_review_period_6",
        "negative_control_permuted",
    ):
        assert key in artifact, f"docs/newsvendor.json is missing the `{key}` run"


def test_the_artifact_carries_a_provenance_git_block(artifact: dict) -> None:
    """
    Every generator under `seeds/` stamps a `git` block (see `seeds/provenance.py`) so a
    reader can tell whether an artifact came from a clean commit. This does not assert
    `dirty is False`: this generator was written and run alongside several other
    concurrent workstreams sharing one tree (see `git log`), so a dirty flag at
    generation time is an expected fact of that sandbox, not a defect in this generator.
    What must hold is that the block exists and is well-formed, so a reader CAN check
    reproducibility later -- `test_docs_match_artifacts.py::
    test_the_leakage_artifact_was_generated_from_a_clean_tree` is the sibling test that
    enforces `dirty is False` once an artifact is committed for real.
    """
    git = artifact["provenance"]["git"]
    assert isinstance(git.get("dirty"), bool)
    assert git.get("commit"), "provenance records no git commit"


def test_the_negative_control_is_not_publishable_and_the_other_four_are(artifact: dict) -> None:
    """The permutation run existing at all is only useful if it is flagged as such."""
    assert artifact["negative_control_permuted"]["ship_gate"]["passed"] is False
    assert "permutation" in artifact["negative_control_permuted"]["ship_gate"]["reason"]
    assert artifact["primary"]["protocol"]["permutation_control"] is False


# ── Section 3.4 must quote the PRIMARY run's own numbers ──────────────────────

def test_section_states_the_panel_size_the_artifact_actually_scored(primary: dict, section: str) -> None:
    panel = primary["panel"]
    assert f"{panel['n_series_scored']:,} of {panel['n_series_available']:,} series" in section
    assert f"{panel['n_decisions']:,} held-out decisions" in section
    # The retired figures from a panel that dropped 3 extra series to a since-fixed defect
    # must not appear as a live claim (the paragraph that explains the fix may still name
    # them historically -- checked separately below).
    if panel["n_series_dropped_pmf_invariant"] == 0:
        assert "2,643 of 2,674" not in section, (
            "the artifact scores a panel with nothing dropped to the invariant defect, but "
            "the doc still quotes the pre-fix 2,643-series panel size as if it were current"
        )


def test_section_states_the_critical_fractile(primary: dict, section: str) -> None:
    tau = primary["costs"]["critical_ratio"]
    assert f"{tau:.4f}" in section


def test_section_headline_table_matches_every_policy_row(primary: dict, section: str) -> None:
    """The eight-column policy table is the load-bearing claim of the whole section."""
    policies = primary["policies"]
    paired = primary["paired_vs_newsvendor"]

    nv = policies["newsvendor_fractile"]
    assert f5(nv["mean_cost_usd_per_sku_period"]) in section
    assert f2(nv["mean_order_quantity"]) in section

    for name in (
        "scarf_minmax", "normal_safety_stock", "safety_multiple_2x",
        "point_forecast", "naive_last", "order_nothing",
    ):
        pol = policies[name]
        p = paired[name]
        assert f5(pol["mean_cost_usd_per_sku_period"]) in section, name
        assert f2(pol["mean_order_quantity"]) in section, name
        assert f5(p["mean_difference"]) in section, name
        assert f5(p["ci95_low"]) in section, f"{name} ci95_low"
        assert f5(p["ci95_high"]) in section, f"{name} ci95_high"
        assert pct1(p["pct_cost_reduction"]) + "%" in section, name


def test_section_states_every_ci_excludes_zero(primary: dict) -> None:
    """Section 3.4 asserts 'every CI excludes zero' for the headline table -- verify it."""
    for name, p in primary["paired_vs_newsvendor"].items():
        assert p["significant"] is True, f"{name}: CI does not exclude zero, but the doc says it does"
    assert primary["ship_gate"]["passed"] is True


def test_section_method_leaderboard_matches_the_artifact(primary: dict, section: str) -> None:
    board = primary["method_leaderboard"]
    for method in ("tsb", "climatology", "naive_last", "sba", "croston", "zero"):
        assert f5(board["decision_cost_usd_per_sku_period"][method]) in section, method
        assert f4(board["mase_mean"][method]) in section, method
    assert board["order_by_mase"][0] == "zero"
    assert board["order_by_decision_cost"][-1] == "zero"
    assert board["order_by_decision_cost"][0] == "tsb"
    assert board["winner_changed"] is True


def test_zero_is_worst_by_the_percentage_the_doc_states(primary: dict, section: str) -> None:
    board = primary["method_leaderboard"]["decision_cost_usd_per_sku_period"]
    pct_above = 100.0 * (board["zero"] - board["tsb"]) / board["tsb"]
    m = re.search(r"worst decision cost of the six\*\*, (\d+)% above the winner", section)
    assert m, "section does not state 'worst decision cost of the six ... N% above the winner'"
    assert int(m.group(1)) == round(pct_above), (
        f"doc says {m.group(1)}% above the winner; artifact implies {pct_above:.1f}%"
    )


# ── Section 3.4 must quote each SENSITIVITY run's own numbers ────────────────

def test_section_line_down_sensitivity_matches_the_artifact(artifact: dict, section: str) -> None:
    run = artifact["sensitivity_line_down"]
    tau = run["costs"]["critical_ratio"]
    paired = run["paired_vs_toughest_baseline"]
    assert f"{tau:.4f}" in section
    assert f5(paired["mean_difference"]) in section
    assert f5(paired["ci95_low"]) in section
    assert f5(paired["ci95_high"]) in section
    assert run["ship_gate"]["passed"] is False, (
        "the artifact's line_down run now passes the ship gate, but the doc calls it an "
        "honest failure"
    )
    assert "does not pass the gate" in section


def test_section_review_period_3_sensitivity_matches_the_artifact(artifact: dict, section: str) -> None:
    run = artifact["sensitivity_review_period_3"]
    tau = run["costs"]["critical_ratio"]
    paired = run["paired_vs_newsvendor"]["point_forecast"]
    assert f"{tau:.4f}" in section
    assert paired["mean_difference"] < 0, "the doc says the L=3 policy LOSES to the point forecast"
    assert f5(abs(paired["mean_difference"])) in section
    assert f5(paired["ci95_low"]) in section
    assert f5(paired["ci95_high"]) in section
    assert "LOSES" in section


def test_section_review_period_6_sensitivity_matches_the_artifact(artifact: dict, section: str) -> None:
    run = artifact["sensitivity_review_period_6"]
    paired = run["paired_vs_newsvendor"]["point_forecast"]
    assert paired["mean_difference"] > 0, "the doc says the L=6 policy wins again"
    assert f5(paired["mean_difference"]) in section
    assert f5(paired["ci95_low"]) in section
    assert f5(paired["ci95_high"]) in section
    assert "wins again" in section


def test_section_negative_control_matches_the_artifact(artifact: dict, section: str) -> None:
    real_cost = artifact["primary"]["policies"]["newsvendor_fractile"]["mean_cost_usd_per_sku_period"]
    fake_cost = artifact["negative_control_permuted"]["policies"]["newsvendor_fractile"][
        "mean_cost_usd_per_sku_period"
    ]
    pct_increase = 100.0 * (fake_cost - real_cost) / real_cost

    assert f"{real_cost:.4f}" in section
    assert f"{fake_cost:.4f}" in section
    m = re.search(r"\(\*\*\+(\d+)%\*\*\)", section)
    assert m, "section does not state the negative control's percentage cost increase"
    assert int(m.group(1)) == round(pct_increase), (
        f"doc says +{m.group(1)}%; artifact implies +{pct_increase:.1f}%"
    )
    assert artifact["negative_control_permuted"]["ship_gate"]["passed"] is False


# ── The since-fixed defect: the doc must not claim it is still open ──────────

def test_the_defect_paragraph_does_not_claim_the_fix_is_still_missing(section: str) -> None:
    """
    The original wording said the fix 'has not been made'. It was made in the same commit
    that shipped this newsvendor layer (`app/ml/intermittent.py::_size_shape`), so a section
    still asserting it is missing would be describing code that no longer exists.
    """
    assert "has not been made" not in section
    assert "fix has since landed" in section or "since fixed" in section


def test_the_defect_no_longer_fires_on_the_committed_panel(primary: dict) -> None:
    """The artifact is the proof the fix landed: nothing is dropped to the invariant guard."""
    assert primary["panel"]["n_series_dropped_pmf_invariant"] == 0


def test_intermittent_module_actually_contains_the_numerical_guard(primary: dict) -> None:
    """
    Belt and suspenders: the doc's claim that `_size_shape` now guards the Poisson limit
    numerically is checked against the source file, not just against the artifact's
    zero-dropped count (which a different bug could also produce).
    """
    del primary
    source = (BACKEND_ROOT / "app" / "ml" / "intermittent.py").read_text()
    assert "_size_shape" in source
    assert "1e-9" in source, (
        "app/ml/intermittent.py no longer contains the numerical Poisson-limit guard "
        "(dispersion below one part in 1e9 of the mean) that Section 3.4 says was added"
    )


# ── Test count sanity ──────────────────────────────────────────────────────────

def test_section_states_the_actual_number_of_tests_in_the_suite(section: str) -> None:
    import subprocess
    import sys

    out = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "tests/test_newsvendor.py"],
        cwd=str(BACKEND_ROOT),
        capture_output=True,
        text=True,
        timeout=60,
    )
    m = re.search(r"(\d+) tests? collected", out.stdout)
    if not m:
        pytest.skip("could not collect tests/test_newsvendor.py to verify the count")
    n = int(m.group(1))
    assert f"({n} tests)" in section, (
        f"tests/test_newsvendor.py collects {n} tests; the doc states a different count"
    )


# ── The Swagger surface is published too ──────────────────────────────────────
# Added 2026-08-28. The module docstring and the `/newsvendor/evaluation` docstring
# both advertised "2,643 held-out series" while the endpoint returned 2,646 -- the
# `_size_shape` Poisson-limit fix let three previously-dropped series survive, and
# the prose was never updated. Item 16 built a doc-vs-artifact gate for
# RESEARCH_TECHNIQUES.md §3.4 but nothing guarded the docstrings, which are the
# copy a reader meets FIRST on public Swagger.

API_MODULE = BACKEND_ROOT / "app" / "api" / "newsvendor.py"

def test_every_series_count_in_the_swagger_docstrings_matches_the_artifact():
    """No number in the API's own prose may disagree with what it returns.

    Reads the artifact `run_panel_evaluation` produced, never another doc.
    """
    artifact = json.loads(ARTIFACT_PATH.read_text())
    scored = artifact["primary"]["panel"]["n_series_scored"]
    source = API_MODULE.read_text()

    claims = re.findall(r"([\d],[\d]{3}) held-out", source)
    assert claims, (
        "no 'N,NNN held-out' claim found in app/api/newsvendor.py -- if the wording "
        "changed, update this regex rather than deleting the guard"
    )
    for claim in claims:
        assert int(claim.replace(",", "")) == scored, (
            f"Swagger says {claim} held-out series; docs/newsvendor.json says "
            f"{scored:,}. Fix the docstring, not this test."
        )


def test_the_swagger_decision_count_matches_the_artifact():
    """Same guard for the decision count, which drifted with the series count."""
    artifact = json.loads(ARTIFACT_PATH.read_text())
    decisions = artifact["primary"]["panel"]["n_decisions"]
    source = API_MODULE.read_text()

    stale = re.findall(r"([\d]{2},[\d]{3}) (?:held-out )?decisions", source)
    for claim in stale:
        assert int(claim.replace(",", "")) == decisions, (
            f"Swagger says {claim} decisions; docs/newsvendor.json says {decisions:,}."
        )
