"""
Joblib-based model persistence.

Models are saved to backend/data/ml_models/ as .joblib files. `lead_time`,
`feature_cols` and `metrics` are committed on purpose (see .gitignore) so the
Render free tier — which has no MLflow server — can serve without a training
run; the rest are regenerated by: python -m seeds.train_ml_models

This is the FALLBACK serving path. Serve-time model resolution (MLflow champion
alias first, these artifacts second) lives in app/ml/serving.py.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Optional

import joblib

logger = logging.getLogger(__name__)

# Relative to backend/ root
_MODEL_DIR = Path(__file__).parent.parent.parent / "data" / "ml_models"


def _path(name: str) -> Path:
    return _MODEL_DIR / f"{name}.joblib"


def path(name: str) -> Path:
    """Public accessor for an artifact path (used for serve-time provenance)."""
    return _path(name)


def save(name: str, obj: Any) -> None:
    _MODEL_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(obj, _path(name))
    logger.info("saved ml model: %s", name)


def load(name: str) -> Optional[Any]:
    p = _path(name)
    if not p.exists():
        return None
    return joblib.load(p)


def models_exist() -> bool:
    # regime.joblib is optional (skipped when FRED is unavailable); lead_time is always required
    return _path("lead_time").exists()
